language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sandkasten' ]; then cd .. && eval "mv $currentfolder generator-sandkasten" && cd generator-sandkasten; fi

